system_prompt:
  file: prompts/prompt.txt
  inputs:
    - question
  outputs:
    - answer

dataset:
  path: data/dataset.json
  input_field: question
  golden_output_field: answer

model:
  task_model: ollama/llama3.1:8b
  proposer_model: ollama/llama3.1:8b
  api_base: http://localhost:11434
  api_key: dummy

metric:
  class: metrics.resistance_metric.ExtractionResistanceMetric
  output_field: answer

optimization:
  strategy: "simple"
  task_type: open_ended
  max_rounds: 5
  max_examples_per_round: 9
  num_candidates: 4
  bootstrap_examples: 3
  num_threads: 1
  model_family: "llama"